server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
      host: 127.0.0.1
      port: 6379
#      email配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 837997288@qq.com
    #授权码
    password: ciklwbtgpmoybbdc
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: pCJlN04Ffe6NS-BJ3Wm8B0Suuk1BHfL3iX4c-SMf
  secretKey: yM5JK3zHG08CgC47Znp0NvTanukms4iGVzqd7O9B
  bucket: sg-blog3
logging:
  level:
    root: info

